apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-appstudio/internal-services/config/crd?ref=5ed462fefb678743a1fe0cc21c205dc838667065

namespace: release-service
